name: 'aeroflux_transform'
version: '1.0.0'

profile: 'aeroflux_transform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Materialization configurations
models:
  aeroflux_transform:
    staging:
      +materialized: view
    marts:
      +materialized: table